name: Main build

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ghcr.io
  BRANCH: main
  #MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
  #GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  #GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}

jobs:
  build-wrapping:
    name: Build Maven source code and Docker image for development Maven registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: checkout local action
        uses: actions/checkout@v2.3.4 
        
      - name: Setup GPG Secrets and custom settings.xml
        uses: ./.github/actions/gpg.yaml
        with:
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}

        
      - name: print settings.xml
        run: |
         cat /home/runner/work/gpg/settings.xml